[tool.poetry]
name = "practical-dl"
version = "0.1.0"
description = ""
authors = ["aseliverstov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.2"
numpy = "<2.0.0"
scikit-learn = "^1.5.2"
ipykernel = "^6.29.5"
matplotlib = "^3.9.2"
tqdm = "^4.66.5"
torch = "^2.4.1"
scikit-image = "^0.24.0"
torchvision = "^0.19.1"
requests = "^2.32.3"
transformers = "^4.45.2"
shap = "^0.46.0"
catboost = "^1.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
